### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by LeonardoRosaa** [dart-code-checker/dart-code-metrics-action#181]
* **Dart Code Metrics GitHub Action version:** v3

**Please show your full configuration:**

<details>

<summary>Configuration</summary>

<br/>
<p><strong>flutter doctor -v:</strong></p>

```
[!] Flutter (Channel stable, 3.10.0, on macOS 13.1 22C65 darwin-arm64, locale en-BR)
    • Flutter version 3.10.0 on channel stable at /Users/leonardo/flutter
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.18.7/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/leonardo/flutter. Consider adding
      /Users/leonardo/flutter/bin to the front of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 84a1e904f4 (3 days ago), 2023-05-09 07:41:44 -0700
    • Engine revision d44b5a94c9
    • Dart version 3.0.0
    • DevTools version 2.23.1
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/leonardo/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14C18
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.78.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)    • chrome • web-javascript • Brave Browser 113.1.51.114

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**What did you do? Please include the source code example causing the issue.**

I have updated the Flutter to the latest version([3.10.0](https://github.com/flutter/flutter/tree/stable)) and all dependencies as possible.

The Dart Code Metrics on my GitHub Actions are below:

```yaml
- name: dart-code-metrics
      uses: dart-code-checker/dart-code-metrics-action@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         relative_path: ./app
         check_unused_files: true
```

**What did you expect to happen?**

Expected that the dart-code-metrics action could check my unused files.

**What actually happened?**

All GitHub Actions are working perfectly but when we start the dart-code-metrics we are getting this exception:

```
Error: Because broad depends on flutter_localizations from sdk which depends on intl 0.17.0, intl 0.17.0 is required.
  So, because broad depends on intl ^0.18.0, version solving failed.
  pub get failed
  command: "/flutter/bin/cache/dart-sdk/bin/dart __deprecated_pub --directory . get --example"
  pub env: {
    "FLUTTER_ROOT": "/flutter",
    "PUB_ENVIRONMENT": "flutter_bot:flutter_cli:get",
    "PUB_CACHE": "/opt/hostedtoolcache/flutter/stable-3.10.0-x64/.pub-cache",
  }
  exit code: 1
  
  
  Unhandled exception:
  Bad state: flutter pub get - returns 1
  #0      getPackageDependencies (package:action_app/package_utils.dart:[25](https://github.com/broad-app/mobile-app/actions/runs/4958883422/jobs/8872303602?pr=1546#step:7:26):5)
  #1      main (file:///action_app/bin/main.dart:28:5)
  #2      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:19)
  #3      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192:[26](https://github.com/broad-app/mobile-app/actions/runs/4958883422/jobs/8872303602?pr=1546#step:7:27))
```

**Comment by dkrutskikh** [comment]
@LeonardoRosaa @felipecastrosales please try to use v4.0.0 pre release version

**Comment by LeonardoRosaa** [comment]
> @LeonardoRosaa @felipecastrosales please try to use v4.0.0 pre release version

That's fixed :)
